"""Add premium fields to User

Revision ID: 8676192a3a07
Revises: 
Create Date: 2026-02-14 14:55:24.954132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8676192a3a07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('premium_quota', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('meetings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('audio_filename', sa.String(length=256), nullable=True),
    sa.Column('audio_path', sa.String(length=512), nullable=True),
    sa.Column('original_language', sa.String(length=50), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('transcript_original', sa.Text(), nullable=True),
    sa.Column('summary_original', sa.Text(), nullable=True),
    sa.Column('action_items_original', sa.JSON(), nullable=True),
    sa.Column('transcript_english', sa.Text(), nullable=True),
    sa.Column('summary_english', sa.Text(), nullable=True),
    sa.Column('action_items_english', sa.JSON(), nullable=True),
    sa.Column('was_translated', sa.Boolean(), nullable=True),
    sa.Column('memo_json', sa.JSON(), nullable=True),
    sa.Column('meeting_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=True),
    sa.Column('data_type', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_user_setting')
    )
    op.create_table('export_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=False),
    sa.Column('export_type', sa.String(length=50), nullable=True),
    sa.Column('recipient', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('export_history')
    op.drop_table('settings')
    op.drop_table('meetings')
    op.drop_table('users')
    # ### end Alembic commands ###
